### ISSUE TITLE
move bin/ directory to OpenVnrmJ repo?

### ISSUE THREAD

**Issue by tesch1** [OpenVnmrJ/ovjTools#10]
it seems like, except for the bin directory, the contents of ovjTools are libraries used by OpenVnmrJ... maybe it would make sense to move the bin dir (build scripts) to OpenVnmrJ and have ovjTools be a (git) submodule of OpenVnmrJ?

I'm working (sporadically) on a travis-ci build, and trying to figure out the best place to put the .travis.yml, and because of the bin dir - I'm currently putting it in ovjTools, but I think it makes more sense to have it in OpenVnmrJ.

Thoughts?

**Comment by tesch1** [comment]
the build so far - https://travis-ci.org/tesch1/ovjTools
travis currently kills it, depending on if the output from makeovj is echoed to the console:
- if it is, it kills the build after 40 mins, because the log is too big
- if it isnt, it kills the build after 10 mins, because it hasnt seen any output and thinks it's hung

**Comment by timburrow** [comment]
The bin directory was moved to ovjTools, as it seemed to make more sense there, then the tools can pull the OpenVnmrJ repo, but the OpenVnmrJ repo could be a submodule or subtree of ovjTools...

Which way make more sense to you?

Thank you for working on travis. I found in a test that the free Travis timed out on me too. We have a server available to us in which I want to install Jenkins. Do you have experience with Jenkins or other CI?

If you want to try Travis, each part of OpenVnmrJ can be built separately (after all the symlinking is done). Maybe breaking it down would be easier.

**Comment by tesch1** [comment]
Travis *should* work, even for this beast - the site says "unlimited build minutes" for the Free plan, and I was up to 40 mins on that build... it just killed it because the output of the build (makeovj) is so verbose. (4 MB limit.)

The next step (to using travis) is probably to make scons less verbose when it's building stuff (like cmake is), I'm still a n00b with scons though, so not sure how to go about that, yet.

To your question - I would think that OpenVnmrJ should be stand-alone and able to build itself, at least for the "datastation only" mode.  And having some of the build scripts in a separate repo seems odd to me.  If the scripts want to build a specific version of OpenVnmrJ, they should just 'git checkout' the right version - and if needed, base off a configuration file that's not checked into the repo.

I dont have any experience with other CI systems; my experience with travis has been pretty good, and it has MacOS support too.

**Comment by tesch1** [comment]
... moving this discussion to the OpenVnmrJ repo ...
https://github.com/OpenVnmrJ/OpenVnmrJ/issues/50
