### ISSUE TITLE
g77 compiler obsolete

### ISSUE THREAD

**Issue by hollaho** [OpenVnmrJ/ovjTools#18]
Build script assumes very old gcc-3 version and fails with gcc-4.9.4 as there is no bin/g77 compiler any more. This is nowadays called gfortran. scons seems to get it wrong:

g77 -o src/DOSY/contin.o -c -fno-f2c -ffast-math -O src/DOSY/contin.for
gcc -o src/3D/sockets.o -c -O2 -Wall -m32 -DHAVE_LARGEFILE_SUPPORT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DLINUX -DFT3DIO -DNOASYNC -Isrc/3D src/3D/sockets.c
sh: g77: command not found
scons: *** [src/DOSY/contin.o] Error 127

Manually editing SConstruct.dosy file to substitute with gfortran does not work, as this file is autogenerated with g77 binary again. The problems seems to lie in OpenVnmrJ/site_scons/darwin.py which does not correctly configure the fortran binary. Forcing this to be gfortran interestingly also did not work, again the SConstruct.dosy contains g77 binary.

Finally the fortran compilation only started working, once doGitClone=no was set in the build script.

**Comment by DanIverson** [comment]
All the fortran compiles now use gfortran
