### ISSUE TITLE
Change filenames to enable build on case-insensitive filesystems (HFS)

### ISSUE THREAD

**Issue by tesch1** [OpenVnmrJ/ovjTools#3]
This is a cosmetic change that would greatly reduce the barriers of participation for some people.

suggest .cc or .cpp, since those seem to be the most common forms.

**Comment by timburrow** [comment]
💯 

I suggest .cpp as it seems more common now and nvpsg has .cpp files.

One more thing; there are a handful of macros and pulse sequences that differ in case only! These need to be enumerated and changed. A simple script could do the enumeration.

**Comment by tesch1** [comment]
moving this here: https://github.com/OpenVnmrJ/OpenVnmrJ/issues/56
