### ISSUE TITLE
Building OVJ in Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by bjohnmr** [OpenVnmrJ/ovjTools#4]
In process of building OpenVnmrJ on Ubuntu 14.04.2 LTS, I ran into the following issues. I was able to build the OpenVnmrJ dvd after some modification of few files. I was building it in Ubuntu 14.04.2 LTS running as a virtual machine in VirtualBox on host Windows 7. 

The issues were-

1) the buildovj script needed some syntax modifications for if/then/elif statements- the lines around 53-56, should be modified as-
if [ "$(uname -s)" = "Darwin" ]
then
  nprocs=$(sysctl -n hw.ncpu)
elif [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]
then
  nprocs=$(nproc)
fi

2) The build script ran into problems with sconsPostAction in the /vnmr/manual directory. I am not sure what exactly the problem was- it seemed to go into a huge loop (infinite?) with the following statements:
cmd:  cd /home/boban/ovjbuild/OpenVnmrJ/../vnmr/manual;chmod +x sconsPostAction; ./sconsPostAction; rm sconsPostAction
./AC1: 2: ./AC1: Cannot fork
./AC1: 3: ./AC1: AC1-9: not found
./AC1: 2: ./AC1: Cannot fork
./AC1: 6: ./AC1: Syntax:: not found
./AC1: 8: ./AC1: Description:: not found
./AC1: 9: ./AC1: The: not found
./AC1: 10: ./AC1: width,: not found
./AC1: 11: ./AC1: determine: not found
./AC1: 12: ./AC1: power.: not found
./AC1: 14: ./AC1: Syntax error: "(" unexpected
./AC1: 3: ./AC1: AC1-9: not found
./AC1: 2: ./AC1: Cannot fork
./AC1: 3: ./AC1: AC1-9: not found
./AC1: 2: ./AC1: Cannot fork
./AC1: 6: ./AC1: Syntax:: not found
./AC1: 8: ./AC1: Description:: not found
./AC1: 9: ./AC1: The: not found
./AC1: 10: ./AC1: width,: not found
.....
The problem was in the build of the manual files and I had to remove both the manual directories 
../ovjbuild/OpenVnmrJ/vnmr/manual, 
../ovjbuild/OpenVnmrJ/src/common/manual. I am suspecting some kind of circular link references in the AC1 and AC9 manual files. I have not investigated this.

3) I was able to build the dvd image successfully after these changes. However, after installation, I ran into a missing file which prevented execution of VnmrJ adm. The missing file is the executable /vnmr/bin/fileowner.

Boban John

**Comment by timburrow** [comment]
Hi Boban,

Sorry to hear that it didn't work! I've tested on CentOS and OS X, but didn't test in on Ubuntu. 

For your points:
1)
The problem is the '==' which should be '='
```
if [ "$(uname -s)" = "Darwin" ]; then
  nprocs=$(sysctl -n hw.ncpu)
elif [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]; then
  nprocs=$(nproc)   
fi
```

I'll fix.

2)
It seems 'AC1' has some text and not a script. This needs further investigation.

3)
fileowner.c compiled OK by itself (you can just paste the code from the repository and compile, if that will help)
```
timothyburrow@ubuntu:~$ vi test.sh 
timothyburrow@ubuntu:~$ vi fileowner.c
timothyburrow@ubuntu:~$ gcc -o fileowner fileowner.c 
timothyburrow@ubuntu:~$ ./fileowner test.sh 
timothyburrow
```

**Comment by bjohnmr** [comment]
Hi Tim,
I compiled the fileowner file and after a couple of other minor modifications, I got OpenVnmrJ running on Ububtu 14.04.2 in  a virtual machine.
Do you know what the state of CRAFT package in the OpenVnmrJ is? Do I need to download/install the Wash U.  Bayesian package separately?
Before Agilent closure, I was with Varian/Agilent working on PSG and instrument control software. Let me know (I will also watch the GitHub ovj) if there are any PSG/Pulse programming issues.I will volunteer to fix some of these issues.
Thanks for your quick response.
Best regards,
Boban

**Comment by bjohnmr** [comment]
OpenVnmrJ is now running on Ubuntu 14.04.2.

**Comment by DanIverson** [comment]
Hi Boban,
How did you resolve the sconsPostAction issue for manuals. For manuals, all it is supposed to do is make soft links for various manuals. There is also a sconsPostAction in maclib. Again, it just makes soft links between various macros. Did that one have any problems?
How did you resolve the fileowner issue?
Dan

**Comment by DanIverson** [comment]
For the CRAFT issue, if /vnmr is linked to VJ42 when you install OpenVnmrJ, then the Bayes part of CRAFT (/vnmr/craft/Bayes3) is copied to OpenVnmrJ from VJ42. Otherwise you will need to get it from the Wash U. website. See the update_OpenVnmrJ script (src/scripts/update_OpenVnmrJ.sh) to see what else is collected from a VJ42 installation for use with OVJ.

**Comment by bjohnmr** [comment]
Dan,
I simply removed the manuals directories from 2 places- 
./ovjbuild/OpenVnmrJ/vnmr/manual, 
../ovjbuild/OpenVnmrJ/src/common/manual.
So I don't have manuals in the installation.
I am suspecting some kind of circular link references in the AC1 and AC9 manual files. I have not investigated this.

I did not change scansPostAction. I am wondering if there is some circular referencing involving AC1 and AC9 files in the manual directories.
I think I individually compile the fileowner.c file as the executable fileowner did not show up after installation. Then I copied it to /vnmr (I think?)
Boban

**Comment by bjohnmr** [comment]
Dan,
In my case I cannot link to VJ4.2. So I guess I have to get it from Wash U website??. Does anybody know which files or the entire Wash U installation. I believe Wash U website has a way to remote install it on your computer.
If you or you know of anybody who has done this, please let me know.
Thanks,
Boban

**Comment by bjohnmr** [comment]
Dan,
I also had to create some small text files in /vnmr/adm/users dir (like userlist file)  to get it all going. vnmrj adm was not quite working from the installation.
Boban
