### ISSUE TITLE
vnmrj not strating - java problem

### ISSUE THREAD

**Issue by UnivMontpellier** [OpenVnmrJ/ovjTools#51]
I'm trying to get the latest version (especially for using the locator) on CentOS 7.9.2009
After compilation and installation, vnmrj is not starting. vnmrj -debug gives 

Exception in thread "main" java.lang.NoClassDefFoundError: vnmr/ui/VNMRFrame
Caused by: java.lang.ClassNotFoundException: vnmr.ui.VNMRFrame
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: vnmr.ui.VNMRFrame.  Program will exit.

I must add that installing and running release openvmrj 2.1A is OK (except the locator problem / welhelp not working / lost of mouse relative position when resizing vnmrj window).

Any help would be appreciated.

**Comment by DanIverson** [comment]
You might try using the java that comes with CentOS 7.9. As OVJ admin (vnmr1?) from a terminal, run
    mv /vnmr/jre  /vnmr/jre_off

**Comment by UnivMontpellier** [comment]
Thanks
using java from CentOS 7.9 just shorten the error message to :
Error: Could not find or load main class vnmr.ui.VNMRFrame

Concerning locator, I'm referring to the "LocatorOff " problem. the database is running OK. But users cannot access it. And we are using it a lot in the lab.

**Comment by DanIverson** [comment]
I just pushed a change that should fix the problem. Just re-run buildovj. You can also use a new feature. Instead of running ./load.nmr, you can run ./upgrade.nmr which will do an in-place upgrade. The new build should also fix the "LocatorOff" problem.

**Comment by UnivMontpellier** [comment]
Great job ... work as expected.
vnmrj starting now. No more LocatorOff warning. Even webhelp is working (it was not working for me with OpenVnmrJ 2.1A release).
Thank you so much. I'm in the process of upgrading our 300 VNMRS spectrometer (solid pack).
I will continue to test it before going to production.
It seems that this issue is closed.

Philippe Gaveau from Montpellier- France

**Comment by UnivMontpellier** [comment]
Already done since it was not solving the issue.
Thank you
