### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by edieladio** [OpenVnmrJ/ovjTools#58]
Trying to install on Linux Mint 20.1 (Ubuntu 20.04) with no success due to obsolete dependences g++-9-multilib (>= 9.3.0-3~) and gcc-9-multilib (>= 9.3.0-3~). Any suggestions?
Thx in advance.

**Comment by DanIverson** [comment]
I am unable to duplicate this problem. Did it occur when running ./toolChain or ./load.nmr

**Comment by edieladio** [comment]
The problem is during ./toolChain
whatsin script shows:
edi@YogaEdi:~/ovjbuild/bin$ ./whatsin
../logs/makeovjlog
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
/usr/include/c++/9/iomanip:38:10: fatal error: bits/c++config.h: No such file or directory
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
src/IMAGE/user_templates/ib_initdir/math/functions/src/ufuncs.c:12:10: fatal error: sys/param.h: No such file or directory
/usr/include/stdlib.h:25:10: fatal error: bits/libc-header-start.h: No such file or directory
scons: *** [asyncIo.o] Error 1
scons: *** [AcodeBuffer.os] Error 1
scons: *** [CSfuncs.o] Error 1
scons: *** [asyncIo.o] Error 1
scons: *** [CSfuncs.o] Error 1
scons: *** [src/IMAGE/user_templates/ib_initdir/math/functions/src/ufuncs.o] Error 1
scons: *** [src/IMAGE/user_templates/ib_initdir/math/functions/src/addms.o] Error 1
scons: building terminated because of errors.
scons: building terminated because of errors.
scons: building terminated because of errors.
scons: building terminated because of errors.
scons: building terminated because of errors.
scons: building terminated because of errors.

In ../logs/makeovjlog there are : 
   Total of  0  ERRORS .
             0  Fatal errors .
             7  fatal errors .
             0  ld: fatal: .
             0  acomp failed .
             0  cannot access .
             0  cannot find .
             7  No such file .
             0  syntax error .
             0  undefined reference .
             7  Error 1 .
             0  Error copying .
             0  does not exist .
             0  Permission denied.
             0  Unable to remove.
             0  File format not recognized.
             0  File exists.
             6  building terminated.
             6  warnings .
I can also attach makeovjlog if desired ;)

Thx

**Comment by edieladio** [comment]
./toolChain shows the annoying error:

edi@YogaEdi:~/ovjbuild/bin$ ./toolChain

If requested, enter the admin (sudo) password
[sudo] password for edi:            
Ign:1 http://dl.google.com/linux/earth/deb stable InRelease
Ign:2 http://ddebs.ubuntu.com focal InRelease                                                                                                                           
Hit:3 http://archive.canonical.com/ubuntu focal InRelease                                                                                                               
Hit:4 http://ppa.launchpad.net/scribus/ppa/ubuntu focal InRelease                                                                                                       
Hit:5 http://archive.ubuntu.com/ubuntu focal InRelease                                                                                                                  
Ign:6 http://ddebs.ubuntu.com focal-updates InRelease                                                                                                                   
Hit:7 https://dl.winehq.org/wine-builds/ubuntu focal InRelease                                                                                                          
Hit:8 http://dl.google.com/linux/earth/deb stable Release                                                                                                               
Hit:9 http://ddebs.ubuntu.com focal Release                                                                                                                             
Hit:10 http://archive.ubuntu.com/ubuntu focal-updates InRelease                                                                                                         
Hit:11 http://ddebs.ubuntu.com focal-updates Release                                                                                                                 
Ign:12 http://packages.linuxmint.com ulyssa InRelease                                                                                                                
Hit:13 https://repo.skype.com/deb stable InRelease                                                                                             
Hit:14 http://archive.ubuntu.com/ubuntu focal-backports InRelease                                                        
Hit:15 http://security.ubuntu.com/ubuntu focal-security InRelease                                                        
Hit:16 https://packages.microsoft.com/repos/ms-teams stable InRelease                              
Hit:17 http://packages.linuxmint.com ulyssa Release                          
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up-to-date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++ is already the newest version (4:9.3.0-1ubuntu2).
g++ set to manually installed.
gcc is already the newest version (4:9.3.0-1ubuntu2).
gfortran is already the newest version (4:9.3.0-1ubuntu2).
gfortran set to manually installed.
libglu1-mesa-dev is already the newest version (9.0.1-1build1).
libglu1-mesa-dev set to manually installed.
make is already the newest version (4.2.1-1.2).
scons is already the newest version (3.1.2-2).
git is already the newest version (1:2.25.1-1ubuntu3.1).
libx11-6 is already the newest version (2:1.6.9-2ubuntu1.2).
libx11-dev is already the newest version (2:1.6.9-2ubuntu1.2).
libx11-6:i386 is already the newest version (2:1.6.9-2ubuntu1.2).
libx11-6:i386 set to manually installed.
libc6-dev is already the newest version (2.31-0ubuntu9.3).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 g++-multilib : Depends: g++-9-multilib (>= 9.3.0-3~) but it is not going to be installed
 gcc-multilib : Depends: gcc-9-multilib (>= 9.3.0-3~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Ubuntu package installation complete

**Comment by DanIverson** [comment]
Apparently, the Mint download mirrors are not equally up to date. Could you use the iso from the USA kernel.org site, which is the one I used. The checksum is
cksum linuxmint-20.1-cinnamon-64bit.iso
914753724 2034827264 linuxmint-20.1-cinnamon-64bit.iso

**Comment by edieladio** [comment]
Finally managed to successfully install.
After googling answer was sudo aptitude install gcc-multilib -> n -> y (to older version)
and then sudo aptitude install g++-multilib
After that ./toolChain worked properly and ./buildovj also. Then ./load.nmr successfully installed the system.

Thx for ur help, DanIverson 😊
